pub mod engine;
pub mod error;
pub mod events;
pub mod executor;
pub mod policy;
pub mod registry;
pub mod request;
pub mod result;

pub use engine::ExecutionEngine;
pub use error::ExecutionError;
pub use error::RegistryError;
pub use events::{ExecutionCompleted, ExecutionFailed, ExecutionRequested};
pub use executor::Executor;
pub use executor::command::CommandExecutor;
pub use executor::file_delete::FileDeleteExecutor;
pub use executor::file_write::FileWriteExecutor;
pub use policy::{CapabilityValidator, ExecutionPolicy};
pub use registry::{ExecutionActionDiscriminant, ExecutorRegistry};
pub use request::{Capability, ExecutionAction, ExecutionRequest};
pub use result::ExecutionResult;
